<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<link rel="stylesheet" type="text/css" media="screen" href="/screen.css" />
<link rel="shortcut icon" href="/images/erlenmeyer-32.png" />
<script type="text/javascript" src="/jquery-1.12.3.min.js"></script>
<script type="text/javascript" src="/jquery-ui.js"></script>
<script type="text/javascript" src="/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="/labpal.js"></script>
<title>${title} - LabPal</title>
</head>
<body>

<div id="main">
<div id="content">

<h1 class="text-only">${title}</h1>
