[User Manual](index.html)

# Including external results

Very often, you are running experiments in order to compare your work with existing results: is my algorithm running faster? Does my procedure provide better precision/recall? Etc.

LabPal provides a convenient way to include existing results and process them side by side with the new results that are generated by your experiments. The principle is simple: it suffices to create new experiments that do not run anything, and rather directly output pre-recorded results.

## <a name="manual">By hand</a>

This could be done by hand. For example, suppose you found this table that advertises sorting times for a (fictional) new algorithm called the "Blabla Sort":

<table border="1">
<tr><th>Array size</th><th>Time (ms)</th></tr>
<tr><td>1000</td><td>14</td></tr>
<tr><td>2000</td><td>24</td></tr>
</table>

You would like to plot these results along with the ones computed by your existing sort experiments. To this end, we can create a new experiment class:

<pre><code>public class BlablaSort extends Experiment {
  public BlablaSort(int size, int time) {
    setInput("Size", size);
    write("Time", time);
    setStatus(Status.DONE);
  }
  
  public void run() {
  }
}
</code>
</pre>

Note how this experiment "hard-codes" its output parameter "Time" directly from a value passed to the constructor, instead of performing an actual sorting and measuring its duration. In consequence, there is nothing to do in method `run`, as the output results for this experiment are already generated. (As a side note, the constructor also already sets the experiment's state to DONE.)

From this point on, instances of BlablaSort can be added to SortingLab, included into tables and plots, like any other experiment.

## <a name="class">Using WriteInExperiment</a>

TODO

<!-- :wrap=soft:mode=markdown: -->