/*
  LabPal, a versatile environment for running experiments on a computer
  Copyright (C) 2015-2022 Sylvain Hallé

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package ca.uqac.lif.labpal.server;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.Calendar;

import ca.uqac.lif.jerrydog.CallbackResponse;
import ca.uqac.lif.jerrydog.Server;
import ca.uqac.lif.jerrydog.CallbackResponse.ContentType;
import ca.uqac.lif.labpal.Laboratory;
import ca.uqac.lif.labpal.Stateful.Status;
import ca.uqac.lif.labpal.macro.Macro;
import ca.uqac.lif.labpal.table.Table;
import ca.uqac.lif.labpal.util.FileHelper;
import ca.uqac.lif.labpal.table.LatexTableRenderer;

import com.sun.net.httpserver.HttpExchange;

/**
 * Callback to download all tables as a single LaTeX file.
 * 
 * @author Sylvain Hallé
 *
 */
public class AllMacrosLatexCallback extends LaboratoryCallback
{
	protected static final String s_barberPoleCode =  FileHelper.internalFileToString(AllPlotsLatexCallback.class, "resource/macro-barber-pole.tex");
	
  public AllMacrosLatexCallback(LabPalServer s)
  {
    super(s, Method.GET, "/macros/tex");
  }

  @Override
  public CallbackResponse process(HttpExchange t)
  {
    CallbackResponse response = new CallbackResponse(t);
    response.setContentType(ContentType.LATEX);
    String filename = Server.urlEncode("labpal-macros.tex");
    response.setAttachment(filename);
    response.setContents(getLatexFile());
    return response;
  }

  /**
   * Generates the LaTeX file
   * 
   * @return The contents of the file
   */
  public String getLatexFile()
  {
    StringBuilder out = new StringBuilder();
    out.append("% ----------------------------------------------------------------")
        .append(FileHelper.CRLF);
    out.append("% File generated by LabPal ").append(Laboratory.s_versionString)
        .append(FileHelper.CRLF);
    out.append("% Date:     ").append(String.format("%1$te-%1$tm-%1$tY", Calendar.getInstance()))
        .append(FileHelper.CRLF);
    out.append("% Lab name: ").append(m_server.getLaboratory().getName()).append(FileHelper.CRLF);
    out.append("%").append(FileHelper.CRLF);
    out.append("% ----------------------------------------------------------------")
        .append(FileHelper.CRLF).append(FileHelper.CRLF);
    out.append(s_barberPoleCode);
    out.append(FileHelper.CRLF);
    for (Macro m : m_server.getLaboratory().getMacros())
    {
    	String macro_name = m.getName();
    	out.append("% ----------------------").append(FileHelper.CRLF).append("% Macro: ")
      .append(macro_name).append(FileHelper.CRLF);
    	out.append("% ----------------------").append(FileHelper.CRLF);
    	Status st = m.getStatus();
      boolean barber_pole = false;
      if (st == Status.FAILED || st == Status.INTERRUPTED)
      {
      	barber_pole = true;
      }
      if (barber_pole)
      {
      	out.append("\\mymacrostripbox{").append(FileHelper.CRLF);
      }
      out.append(m.toLatex());
      if (barber_pole)
      {
      	out.append("}");
      }
      out.append(FileHelper.CRLF);
    }
    return out.toString();
  }
}
